version: '3.7'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 3000:8000
    env_file:
      - ./.env.prod
    depends_on: 
      - db
      - redis
  redis:
    image: "redis:alpine"
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=s3_upload
      - POSTGRES_PASSWORD=s3_upload
      - POSTGRES_DB=s3_upload_dev
  celery:
    build: ./
    command: celery -A app worker -l info
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - db
      - redis
  celery-beat:
    build: ./
    command: celery -A app beat -l info
    volumes:
      - ./:/usr/src/app/
    depends_on:
      - db
      - redis
volumes: 
  postgres_data: