# Generated by Django 3.1.5 on 2021-01-30 17:35

from django.db import migrations, models
import easy_thumbnails.fields
import upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestS3Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=upload.models.upload_to_session_key_dir)),
            ],
        ),
    ]
