# Generated by Django 3.1.5 on 2021-01-26 00:45

from django.db import migrations, models
import django.utils.timezone
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests3upload',
            name='session_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tests3upload',
            name='file',
            field=models.FileField(upload_to=upload.models.upload_to_session_key_dir),
        ),
    ]
